language: python
python:
  - "3.7"
matrix:
  include:

  # default Python + latest Sphinx + check for broken links
  - env: ADDITIONAL_COMMAND="python -m sphinx doc/ doc/_build/ -b linkcheck"

  # a few older Sphinx releases using default Python version
  - env: SPHINX="==1.8.0" BIBTEX="==0.4.2"
  - env: SPHINX="==1.8.5" BIBTEX="==0.4.2"
  - env: SPHINX="==2.0.0"
  - env: SPHINX="==2.1.0"
  - env: SPHINX="==2.1.2"

  # a few Python versions using latest Sphinx release
  - python: "3.4"
    env: BIBTEX="==0.4.2"
  - python: "3.5"
  - python: "3.6"
  - python: "nightly"
  #- python: "pypy3"

addons:
  apt:
    packages:
      - pandoc
      - librsvg2-bin
install:
  - pip install Sphinx$SPHINX
  - pip install .
  - pip install $(grep -iv bibtex doc/requirements.txt)
  - pip install sphinxcontrib-bibtex$BIBTEX
script:
  - python -m nbsphinx
  - python -m sphinx doc/ doc/_build/ -b html
  - python -m sphinx doc/ doc/_build/ -b latex
  - python -m sphinx doc/ doc/_build/ -b epub
  - $ADDITIONAL_COMMAND
