dist: bionic
language: python
python:
  - "3.8"
matrix:
  include:

  - name: default Python + latest Sphinx

  # a few older Sphinx releases using default Python version
  - env: SPHINX="==1.8.1" BIBTEX="==0.4.2"
  - env: SPHINX="==1.8.5" BIBTEX="==0.4.2"
  - env: SPHINX="==2.0.0"
  - env: SPHINX="==2.2.0"
  - env: SPHINX="==2.4.0"
  - env: SPHINX="==3.0.0"
  - env: SPHINX="==3.1.0"

  # a few Python versions using latest Sphinx release
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "nightly"
  - python: "pypy3"

  - name: default Python + latest Sphinx
    os: osx
    language: generic
    python: ""

  allow_failures:
    - python: "nightly"

addons:
  apt:
    packages:
      - pandoc
      - librsvg2-bin
  homebrew:
    update: true
    packages:
      - python
      - pandoc
      - librsvg
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew link --overwrite python; fi
install:
  - python3 --version
  - python3 -m pip install Sphinx$SPHINX
  - python3 -m pip install .
  - python3 -m pip install $(grep -iv bibtex doc/requirements.txt)
  - python3 -m pip install sphinxcontrib-bibtex$BIBTEX
script:
  - python3 -m nbsphinx
  - python3 -m sphinx doc/ _build/ -W -Dsuppress_warnings=git.too_shallow -b html
  - python3 -m sphinx doc/ _build/ -W -Dsuppress_warnings=git.too_shallow -b latex
  - python3 -m sphinx doc/ _build/ -W -Dsuppress_warnings=git.too_shallow,epub.unknown_project_files -b epub
