language: python
python:
  - "3.7"
matrix:
  include:

  - name: default Python + latest Sphinx

  - name: check for broken links
    script:
      - python3 -m sphinx doc/ doc/_build/ -b linkcheck

  # a few older Sphinx releases using default Python version
  - env: SPHINX="==1.8.0" BIBTEX="==0.4.2"
  - env: SPHINX="==1.8.5" BIBTEX="==0.4.2"
  - env: SPHINX="==2.0.0"
  - env: SPHINX="==2.1.0"
  - env: SPHINX="==2.1.2"

  # a few Python versions using latest Sphinx release
  - python: "3.4"
    env: BIBTEX="==0.4.2"
  - python: "3.5"
  - python: "3.6"
  - python: "nightly"
  #- python: "pypy3"

  - name: Python 2.7 + latest Sphinx
    python: "2.7"
    install: &py2-install
      - python2 -m pip install .
      - python2 -m pip install sphinxcontrib-bibtex==0.4.2
      - python2 -m pip install sphinxcontrib-svg2pdfconverter
      - python2 -m pip install ipywidgets
    script: &py2-script
      - python2 -m nbsphinx
      # We don't execute, because the example notebooks use Python 3
      - python2 -m sphinx doc/ doc/_build/ -b html -D nbsphinx_execute=never

  - name: default Python + latest Sphinx
    os: osx
    language: generic

  - name: Python 2.7 + latest Sphinx
    os: osx
    language: generic
    install: *py2-install
    script: *py2-script

addons:
  apt:
    packages:
      - pandoc
      - librsvg2-bin
  homebrew:
    update: true
    packages:
      - pandoc
      - librsvg
      - python3
install:
  - python3 -m pip install Sphinx$SPHINX
  - python3 -m pip install .
  - python3 -m pip install $(grep -iv bibtex doc/requirements.txt)
  - python3 -m pip install sphinxcontrib-bibtex$BIBTEX
script:
  - python3 -m nbsphinx
  - python3 -m sphinx doc/ doc/_build/ -b html
  - python3 -m sphinx doc/ doc/_build/ -b latex
  - python3 -m sphinx doc/ doc/_build/ -b epub
