language: python
python:
  - "3.8"
matrix:
  include:

  - name: default Python + latest Sphinx

  # a few older Sphinx releases using default Python version
  - env: SPHINX="==1.8.1" BIBTEX="==0.4.2"
  - env: SPHINX="==1.8.5" BIBTEX="==0.4.2"
  - env: SPHINX="==2.0.0"
  - env: SPHINX="==2.1.0"
  - env: SPHINX="==2.2.0"

  # a few Python versions using latest Sphinx release
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
  - python: "nightly"
  # - python: "pypy3"

  - name: Python 2.7 + latest Sphinx
    python: "2.7"
    install: &py2-install
      - python2 --version
      - python2 -m pip install .
      - python2 -m pip install sphinxcontrib-bibtex==0.4.2
      - python2 -m pip install sphinxcontrib-svg2pdfconverter
      - python2 -m pip install ipywidgets
      - python2 -m pip install 'sphinx-copybutton<0.2.6'
    script: &py2-script
      - python2 -m nbsphinx
      # We don't execute, because the example notebooks use Python 3
      - python2 -m sphinx doc/ doc/_build/ -W -b html -D nbsphinx_execute=never

  - name: default Python + latest Sphinx
    os: osx
    language: generic
    python: ""

  - name: Python 2.7 + latest Sphinx
    os: osx
    language: generic
    python: ""
    addons:
      homebrew:
        update: true
        packages:
          - python@2
          - pandoc
          - librsvg
    install: *py2-install
    script: *py2-script

  allow_failures:
    - python: "nightly"

addons:
  apt:
    packages:
      - pandoc
      - librsvg2-bin
  homebrew:
    update: true
    packages:
      - python
      - pandoc
      - librsvg
before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew link --overwrite python; fi
install:
  - python3 --version
  - python3 -m pip install Sphinx$SPHINX
  - python3 -m pip install .
  - python3 -m pip install $(grep -iv bibtex doc/requirements.txt)
  - python3 -m pip install sphinxcontrib-bibtex$BIBTEX
script:
  - python3 -m nbsphinx
  - python3 -m sphinx doc/ doc/_build/ -W -b html
  - python3 -m sphinx doc/ doc/_build/ -W -b latex
  - python3 -m sphinx doc/ doc/_build/ -W -b epub
